#!/usr/bin/env python3
"""Write the original compliance corpus JSON files.

Cases are authored here from published normative rules (RFC / YAML / TOML /
MessagePack specs). They are not copied from third-party suites. See
compliance/LEGAL.md.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "data"


def dump(rel: str, doc: dict) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT.parent)} ({len(doc['cases'])} cases)")


def C(
    id: str,
    title: str,
    section: str,
    section_title: str,
    section_url: str,
    paragraph: str,
    requirement: str,
    expect: str,
    input: str,
    *,
    input_encoding: str = "utf-8",
    decoded=None,
    has_decoded: bool = False,
    notes: str = "",
    skip_adapters: list[str] | None = None,
) -> dict:
    item = {
        "id": id,
        "title": title,
        "section": section,
        "section_title": section_title,
        "section_url": section_url,
        "paragraph": paragraph,
        "requirement": requirement,
        "expect": expect,
        "input": input,
        "input_encoding": input_encoding,
    }
    if has_decoded or decoded is not None:
        item["decoded"] = decoded
    if notes:
        item["notes"] = notes
    if skip_adapters:
        item["skip_adapters"] = skip_adapters
    return item


# ---------------------------------------------------------------------------
# JSON shared reject / accept cases
# ---------------------------------------------------------------------------

JSON_INVALID_TRAILING = (
    "A JSON value is object / array / number / string / true / false / null. "
    "A trailing comma is not in the grammar."
)
JSON_INVALID_COMMENT = "The JSON grammar has no comment production."
JSON_INVALID_SINGLE = "A string begins and ends with quotation mark (U+0022), not apostrophe."
JSON_INVALID_NAN = "Numeric values are produced from the number grammar; NaN is not a number token."
JSON_INVALID_LEAD0 = "A number MUST NOT have a leading zero unless the value is zero."
JSON_INVALID_UNQUOTED = "An object member name is a string, which is quoted."
JSON_CTRL = "Unescaped control characters (U+0000 through U+001F) MUST NOT appear in a string."


def json_common_accept(prefix: str, url_base: str, *, top_level_any: bool) -> list[dict]:
    u = lambda sec: f"{url_base}#section-{sec}"
    cases = [
        C(
            f"{prefix}-empty-object",
            "Empty object is a JSON text",
            "2",
            "JSON Grammar",
            u("2"),
            "An object structure is represented as a pair of curly brackets surrounding zero or more name/value pairs.",
            "MUST",
            "accept",
            "{}",
            decoded={},
        ),
        C(
            f"{prefix}-empty-array",
            "Empty array is a JSON text",
            "5",
            "Arrays",
            u("5"),
            "An array structure is represented as square brackets surrounding zero or more values.",
            "MUST",
            "accept",
            "[]",
            decoded=[],
        ),
        C(
            f"{prefix}-object-mixed",
            "Object with string, number, bool, null, nested array",
            "4",
            "Objects",
            u("4"),
            "An object is an unordered collection of zero or more name/value pairs.",
            "MUST",
            "accept",
            '{"harbor":"kelp","count":3,"ok":true,"missing":null,"tags":["a",2]}',
            decoded={"harbor": "kelp", "count": 3, "ok": True, "missing": None, "tags": ["a", 2]},
        ),
        C(
            f"{prefix}-array-heterogeneous",
            "Array may mix JSON types",
            "5",
            "Arrays",
            u("5"),
            "There is no requirement that the values in an array be of the same type.",
            "MUST",
            "accept",
            '[1,"x",false,null,{"k":1}]',
            decoded=[1, "x", False, None, {"k": 1}],
        ),
        C(
            f"{prefix}-string-escapes",
            "Standard escape sequences",
            "7",
            "Strings",
            u("7"),
            r'All Unicode characters may be placed within quotation marks except those that must be escaped: quotation mark, reverse solidus, and the control characters. Short escapes include \", \\, \/, \b, \f, \n, \r, \t, and \uXXXX.',
            "MUST",
            "accept",
            r'{"s":"line\nquote\"slash\\tab\t"}' if not top_level_any else r'"line\nquote\"slash\\tab\t"',
            decoded={"s": 'line\nquote"slash\\tab\t'} if not top_level_any else 'line\nquote"slash\\tab\t',
        ),
        C(
            f"{prefix}-string-unicode",
            "Unicode code point via \\u and literal UTF-8",
            "7",
            "Strings",
            u("7"),
            "Any code point may be represented as a hexadecimal escape; UTF-8 is the interchange encoding of the text.",
            "MUST",
            "accept",
            '{"s":"café \\u00e9"}' if not top_level_any else '"café \\u00e9"',
            decoded={"s": "café é"} if not top_level_any else "café é",
        ),
        C(
            f"{prefix}-number-int",
            "Integer without leading zero",
            "6",
            "Numbers",
            u("6"),
            "A number contains an integer component that may be prefixed with a minus sign.",
            "MUST",
            "accept",
            "[-17]" if not top_level_any else "-17",
            decoded=[-17] if not top_level_any else -17,
        ),
        C(
            f"{prefix}-number-frac-exp",
            "Fractional number with exponent",
            "6",
            "Numbers",
            u("6"),
            "A number may have a fractional part and/or an exponent part.",
            "MUST",
            "accept",
            "[1.5e2]" if not top_level_any else "1.5e2",
            decoded=[150.0] if not top_level_any else 150.0,
        ),
        C(
            f"{prefix}-ws-around",
            "Insignificant whitespace around a value",
            "2",
            "JSON Grammar",
            u("2"),
            "Whitespace may be inserted between any pair of tokens.",
            "MUST",
            "accept",
            "  { \"n\" : 1 }  ",
            decoded={"n": 1},
        ),
    ]
    if top_level_any:
        cases.extend(
            [
                C(
                    f"{prefix}-top-string",
                    "A JSON text may be a string",
                    "2",
                    "JSON Grammar",
                    u("2"),
                    "A JSON text is a serialized value. Note that this is different from RFC 4627, which allowed only object or array at the top level.",
                    "MUST",
                    "accept",
                    '"harbor"',
                    decoded="harbor",
                ),
                C(
                    f"{prefix}-top-number",
                    "A JSON text may be a number",
                    "2",
                    "JSON Grammar",
                    u("2"),
                    "A JSON text is a serialized value.",
                    "MUST",
                    "accept",
                    "0",
                    decoded=0,
                ),
                C(
                    f"{prefix}-top-true",
                    "A JSON text may be true",
                    "3",
                    "Values",
                    u("3"),
                    "A JSON value MUST be an object, array, number, or string, or one of the literal names true, false, or null.",
                    "MUST",
                    "accept",
                    "true",
                    decoded=True,
                ),
                C(
                    f"{prefix}-top-null",
                    "A JSON text may be null",
                    "3",
                    "Values",
                    u("3"),
                    "A JSON value MUST be an object, array, number, or string, or one of the literal names true, false, or null.",
                    "MUST",
                    "accept",
                    "null",
                    decoded=None,
                ),
            ]
        )
    else:
        cases.extend(
            [
                C(
                    f"{prefix}-top-string-forbidden",
                    "RFC 4627 forbids a top-level string",
                    "2",
                    "JSON Grammar",
                    u("2"),
                    "A JSON text is a serialized object or array.",
                    "MUST",
                    "reject",
                    '"harbor"',
                ),
                C(
                    f"{prefix}-top-number-forbidden",
                    "RFC 4627 forbids a top-level number",
                    "2",
                    "JSON Grammar",
                    u("2"),
                    "A JSON text is a serialized object or array.",
                    "MUST",
                    "reject",
                    "0",
                ),
                C(
                    f"{prefix}-top-true-forbidden",
                    "RFC 4627 forbids a top-level literal",
                    "2",
                    "JSON Grammar",
                    u("2"),
                    "A JSON text is a serialized object or array.",
                    "MUST",
                    "reject",
                    "true",
                ),
            ]
        )
    return cases


def json_common_reject(prefix: str, url_base: str) -> list[dict]:
    u = lambda sec: f"{url_base}#section-{sec}"
    return [
        C(
            f"{prefix}-trailing-comma-object",
            "Trailing comma after the last object member is invalid",
            "4",
            "Objects",
            u("4"),
            JSON_INVALID_TRAILING,
            "MUST NOT",
            "reject",
            '{"harbor":1,}',
        ),
        C(
            f"{prefix}-trailing-comma-array",
            "Trailing comma after the last array element is invalid",
            "5",
            "Arrays",
            u("5"),
            JSON_INVALID_TRAILING,
            "MUST NOT",
            "reject",
            "[1,2,]",
        ),
        C(
            f"{prefix}-single-quotes",
            "Single-quoted strings are not JSON",
            "7",
            "Strings",
            u("7"),
            JSON_INVALID_SINGLE,
            "MUST NOT",
            "reject",
            "{'harbor':1}",
        ),
        C(
            f"{prefix}-comment",
            "C-style comments are not JSON",
            "2",
            "JSON Grammar",
            u("2"),
            JSON_INVALID_COMMENT,
            "MUST NOT",
            "reject",
            '{"harbor":1} // note',
        ),
        C(
            f"{prefix}-bare-nan",
            "NaN is not a JSON number",
            "6",
            "Numbers",
            u("6"),
            JSON_INVALID_NAN,
            "MUST NOT",
            "reject",
            "NaN",
        ),
        C(
            f"{prefix}-infinity",
            "Infinity is not a JSON number",
            "6",
            "Numbers",
            u("6"),
            "Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not permitted.",
            "MUST NOT",
            "reject",
            "Infinity",
        ),
        C(
            f"{prefix}-leading-zero",
            "Leading zeros are not allowed",
            "6",
            "Numbers",
            u("6"),
            JSON_INVALID_LEAD0,
            "MUST NOT",
            "reject",
            "01",
        ),
        C(
            f"{prefix}-unquoted-key",
            "Object member names must be strings",
            "4",
            "Objects",
            u("4"),
            JSON_INVALID_UNQUOTED,
            "MUST NOT",
            "reject",
            "{harbor:1}",
        ),
        C(
            f"{prefix}-unescaped-newline",
            "Unescaped U+000A in a string is invalid",
            "7",
            "Strings",
            u("7"),
            JSON_CTRL,
            "MUST NOT",
            "reject",
            '"line\nbreak"',
        ),
        C(
            f"{prefix}-empty",
            "The empty document is not a JSON text",
            "2",
            "JSON Grammar",
            u("2"),
            "A JSON text is a serialized value (RFC 7159/8259) or object/array (RFC 4627).",
            "MUST",
            "reject",
            "",
        ),
        C(
            f"{prefix}-extra-value",
            "Two top-level values are not a single JSON text",
            "2",
            "JSON Grammar",
            u("2"),
            "A JSON text is one serialized value.",
            "MUST NOT",
            "reject",
            "true false",
        ),
        C(
            f"{prefix}-true-wrong-case",
            "Literal names are lowercase only",
            "3",
            "Values",
            u("3"),
            "The literal names MUST be lowercase. No other literal names are allowed.",
            "MUST NOT",
            "reject",
            "True",
        ),
    ]


def write_json_suites() -> None:
    r4627 = "https://www.rfc-editor.org/rfc/rfc4627"
    r7159 = "https://www.rfc-editor.org/rfc/rfc7159"
    r8259 = "https://www.rfc-editor.org/rfc/rfc8259"
    r7493 = "https://www.rfc-editor.org/rfc/rfc7493"

    dump(
        "json/rfc4627.json",
        {
            "format": "json",
            "standard": "RFC 4627",
            "version": "4627",
            "standard_url": r4627,
            "provenance": "original-work",
            "notes": (
                "RFC 4627 (July 2006) is the first IETF JSON document. A JSON text is a "
                "serialized object or array. Obsoleted by RFC 7159."
            ),
            "cases": json_common_accept("json-4627", r4627, top_level_any=False)
            + json_common_reject("json-4627", r4627),
        },
    )
    dump(
        "json/rfc7159.json",
        {
            "format": "json",
            "standard": "RFC 7159",
            "version": "7159",
            "standard_url": r7159,
            "provenance": "original-work",
            "notes": (
                "RFC 7159 (March 2014) allows any JSON value at the top level and permits "
                "UTF-8, UTF-16, or UTF-32. Obsoleted by RFC 8259."
            ),
            "cases": json_common_accept("json-7159", r7159, top_level_any=True)
            + json_common_reject("json-7159", r7159)
            + [
                C(
                    "json-7159-utf16le-object",
                    "RFC 7159 allows UTF-16 (BOM + empty object)",
                    "8.1",
                    "Character Encoding",
                    f"{r7159}#section-8.1",
                    "JSON text SHALL be encoded in Unicode. The default encoding is UTF-8. UTF-16 and UTF-32 are also permitted.",
                    "MUST",
                    "accept",
                    "fffe7b007d00",
                    input_encoding="hex",
                    decoded={},
                    notes=(
                        "Many production parsers only implement UTF-8. A reject here is a "
                        "7159 deviation, not an 8259 defect."
                    ),
                ),
            ],
        },
    )
    dump(
        "json/rfc8259.json",
        {
            "format": "json",
            "standard": "RFC 8259",
            "version": "8259",
            "standard_url": r8259,
            "provenance": "original-work",
            "notes": (
                "RFC 8259 (December 2017) is Internet Standard 90. Interchange JSON text "
                "MUST be UTF-8. Aligned with ECMA-404 2nd edition."
            ),
            "cases": json_common_accept("json-8259", r8259, top_level_any=True)
            + json_common_reject("json-8259", r8259)
            + [
                C(
                    "json-8259-utf16le-forbidden",
                    "RFC 8259 interchange encoding is UTF-8 only",
                    "8.1",
                    "Character Encoding",
                    f"{r8259}#section-8.1",
                    "JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8.",
                    "MUST",
                    "reject",
                    "fffe7b007d00",
                    input_encoding="hex",
                ),
                C(
                    "json-8259-duplicate-keys",
                    "The names within an object SHOULD be unique",
                    "4",
                    "Objects",
                    f"{r8259}#section-4",
                    "The names within an object SHOULD be unique. When they are not, the behavior is unpredictable across implementations.",
                    "SHOULD",
                    "accept",
                    '{"harbor":1,"harbor":2}',
                    notes=(
                        "SHOULD, not MUST. Recording which value wins (first vs last) is "
                        "useful; both accepting and taking one of the values is common."
                    ),
                ),
                C(
                    "json-8259-surrogate-pair",
                    "A proper UTF-16 surrogate pair in \\u escapes",
                    "8.2",
                    "Unicode Characters",
                    f"{r8259}#section-8.2",
                    "To escape a code point that is not in the Basic Multilingual Plane, the character may be represented as a twelve-character sequence encoding the UTF-16 surrogate pair.",
                    "MUST",
                    "accept",
                    r'"\uD83D\uDE00"',
                    decoded="😀",
                ),
                C(
                    "json-8259-lone-surrogate",
                    "Unpaired surrogates are not Unicode scalar values",
                    "8.2",
                    "Unicode Characters",
                    f"{r8259}#section-8.2",
                    "The hex escape form may represent unpaired surrogates; software that interprets JSON as Unicode text may reject them. I-JSON forbids them.",
                    "SHOULD NOT",
                    "reject",
                    r'"\uD800"',
                    notes="RFC 8259 does not forbid unpaired surrogates in the grammar; I-JSON does. Recorded as SHOULD NOT for interchange.",
                ),
            ],
        },
    )
    dump(
        "json/rfc7493-ijson.json",
        {
            "format": "json",
            "standard": "RFC 7493 I-JSON",
            "version": "7493",
            "standard_url": r7493,
            "provenance": "original-work",
            "notes": (
                "I-JSON is a restricted profile of JSON for Internet protocols. It is not "
                "a fourth JSON grammar; it constrains how JSON is used."
            ),
            "cases": [
                C(
                    "ijson-top-object",
                    "I-JSON messages should be objects (or arrays)",
                    "4.1",
                    "Top-Level Constructs",
                    f"{r7493}#section-4.1",
                    "An I-JSON message can be any JSON value. However, older RFC 4627 implementations only accept objects or arrays at the top level; protocols are advised to use an object or array.",
                    "SHOULD",
                    "accept",
                    '{"harbor":"kelp"}',
                    decoded={"harbor": "kelp"},
                ),
                C(
                    "ijson-utf8-only",
                    "I-JSON text is UTF-8",
                    "2.1",
                    "Encoding and Characters",
                    f"{r7493}#section-2.1",
                    "I-JSON messages MUST be encoded using UTF-8.",
                    "MUST",
                    "reject",
                    "fffe7b007d00",
                    input_encoding="hex",
                ),
                C(
                    "ijson-no-lone-surrogate",
                    "I-JSON forbids unpaired surrogates",
                    "2.1",
                    "Encoding and Characters",
                    f"{r7493}#section-2.1",
                    "I-JSON messages MUST NOT include characters or escape sequences that represent unpaired UTF-16 surrogates or noncharacter code points.",
                    "MUST NOT",
                    "reject",
                    r'"\uD800"',
                ),
                C(
                    "ijson-no-duplicate-keys",
                    "I-JSON objects MUST have unique member names",
                    "2.3",
                    "Object Constraints",
                    f"{r7493}#section-2.3",
                    "Objects in I-JSON messages MUST have unique member names.",
                    "MUST",
                    "reject",
                    '{"harbor":1,"harbor":2}',
                    notes="Most JSON parsers accept this and keep one value. That is an I-JSON profile miss, not an RFC 8259 grammar miss.",
                ),
                C(
                    "ijson-binary64-number",
                    "Numbers should be IEEE 754 binary64",
                    "2.2",
                    "Numbers",
                    f"{r7493}#section-2.2",
                    "I-JSON messages SHOULD NOT include numbers that look like integers but cannot be represented as an IEEE 754-2008 binary64 value without loss.",
                    "SHOULD NOT",
                    "accept",
                    "9007199254740993",
                    notes="2^53+1 is not exactly representable in binary64. Parsers that silently coerce to 9007199254740992 lose an I-JSON guarantee.",
                ),
                C(
                    "ijson-no-nan",
                    "NaN is outside I-JSON (and JSON)",
                    "2.2",
                    "Numbers",
                    f"{r7493}#section-2.2",
                    "I-JSON is a profile of JSON; NaN is not a JSON number.",
                    "MUST NOT",
                    "reject",
                    "NaN",
                ),
            ],
        },
    )


# ---------------------------------------------------------------------------
# YAML
# ---------------------------------------------------------------------------


def write_yaml_suites() -> None:
    y11 = "https://yaml.org/spec/1.1/"
    y12 = "https://yaml.org/spec/1.2/spec.html"
    y122 = "https://yaml.org/spec/1.2.2/"

    dump(
        "yaml/v1.1.json",
        {
            "format": "yaml",
            "standard": "YAML 1.1",
            "version": "1.1",
            "standard_url": y11,
            "provenance": "original-work",
            "notes": (
                "YAML 1.1 (2005) is what PyYAML implements by default. Booleans include "
                "yes/no/on/off; sexagesimal numbers exist."
            ),
            "cases": [
                C(
                    "yaml11-block-mapping",
                    "Block mapping of scalars",
                    "3.2.1.1",
                    "Mapping",
                    f"{y11}#id864410",
                    "A mapping node represents an association of key/value pairs.",
                    "MUST",
                    "accept",
                    "harbor: kelp\ncount: 3\n",
                    decoded={"harbor": "kelp", "count": 3},
                ),
                C(
                    "yaml11-block-sequence",
                    "Block sequence",
                    "3.2.1.1",
                    "Sequence",
                    f"{y11}#id864410",
                    "A sequence node represents an ordered series of nodes.",
                    "MUST",
                    "accept",
                    "- red\n- green\n- blue\n",
                    decoded=["red", "green", "blue"],
                ),
                C(
                    "yaml11-flow-jsonish",
                    "Flow mapping and sequence (JSON-like)",
                    "9.2",
                    "Flow styles",
                    f"{y11}#id2545072",
                    "Flow collections use explicit indicators similar to JSON.",
                    "MUST",
                    "accept",
                    '{"harbor": "kelp", "tags": [1, 2]}\n',
                    decoded={"harbor": "kelp", "tags": [1, 2]},
                ),
                C(
                    "yaml11-bool-yes",
                    "Plain scalar yes is a boolean in YAML 1.1",
                    "10.2.1.2",
                    "Boolean Language-Independent Type",
                    f"{y11}#id2804923",
                    "YAML 1.1 resolves y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF to booleans.",
                    "MUST",
                    "accept",
                    "flag: yes\n",
                    decoded={"flag": True},
                ),
                C(
                    "yaml11-bool-off",
                    "Plain scalar off is a boolean in YAML 1.1",
                    "10.2.1.2",
                    "Boolean Language-Independent Type",
                    f"{y11}#id2804923",
                    "off is a canonical boolean false in the YAML 1.1 type repository.",
                    "MUST",
                    "accept",
                    "flag: off\n",
                    decoded={"flag": False},
                ),
                C(
                    "yaml11-null-tilde",
                    "Tilde is null",
                    "10.2.1.1",
                    "Null Language-Independent Type",
                    f"{y11}#id2805071",
                    "A tilde (~) or the empty scalar may resolve to null.",
                    "MUST",
                    "accept",
                    "missing: ~\n",
                    decoded={"missing": None},
                ),
                C(
                    "yaml11-anchor-alias",
                    "Anchor and alias reuse a node",
                    "3.2.2.2",
                    "Anchors and Aliases",
                    f"{y11}#id863921",
                    "An alias node refers to the most recent node having the same anchor.",
                    "MUST",
                    "accept",
                    "first: &harbor kelp\nsecond: *harbor\n",
                    decoded={"first": "kelp", "second": "kelp"},
                ),
                C(
                    "yaml11-quoted-yes",
                    "Quoted yes remains a string",
                    "9.1",
                    "Double-quoted scalars",
                    f"{y11}#id2545157",
                    "Quoted scalars are not subject to implicit type resolution.",
                    "MUST",
                    "accept",
                    'flag: "yes"\n',
                    decoded={"flag": "yes"},
                ),
                C(
                    "yaml11-sexagesimal",
                    "Sexagesimal integers exist in YAML 1.1",
                    "10.2.1.3",
                    "Integer Language-Independent Type",
                    f"{y11}#id2803828",
                    "YAML 1.1 integers include base-60 sexagesimal values such as 1:2 (62).",
                    "MUST",
                    "accept",
                    "clock: 1:2\n",
                    decoded={"clock": 62},
                    notes="YAML 1.2 removed sexagesimal. PyYAML 1.1 loaders typically produce 62.",
                ),
                C(
                    "yaml11-tab-indent",
                    "Tab characters must not be used for indentation",
                    "4.1.1",
                    "Indentation Spaces",
                    f"{y11}#id871692",
                    "In YAML block styles, indentation is defined by space characters. Tab characters must not be used.",
                    "MUST NOT",
                    "reject",
                    "harbor:\n\tkelp\n",
                ),
                C(
                    "yaml11-unmatched-quote",
                    "Unterminated quoted scalar is an error",
                    "9.1",
                    "Double-quoted scalars",
                    f"{y11}#id2545157",
                    "A double-quoted scalar must be closed by a matching quotation mark.",
                    "MUST NOT",
                    "reject",
                    'harbor: "kelp\n',
                ),
            ],
        },
    )
    dump(
        "yaml/v1.2.json",
        {
            "format": "yaml",
            "standard": "YAML 1.2",
            "version": "1.2",
            "standard_url": y12,
            "provenance": "original-work",
            "notes": (
                "YAML 1.2 (2009) makes JSON an official subset and drops YAML 1.1 "
                "implicit types such as yes/no booleans in the JSON and Core schemas."
            ),
            "cases": [
                C(
                    "yaml12-json-subset-object",
                    "A JSON object is a YAML 1.2 document",
                    "1.3",
                    "Revision 1.2 Goals",
                    f"{y12}#id2759572",
                    "YAML 1.2 was revised to bring YAML into compliance with JSON as an official subset.",
                    "MUST",
                    "accept",
                    '{"harbor":"kelp","count":3}',
                    decoded={"harbor": "kelp", "count": 3},
                ),
                C(
                    "yaml12-json-true-false-null",
                    "JSON true/false/null tokens",
                    "10.2.2",
                    "JSON Schema",
                    f"{y12}#id2803231",
                    "The JSON schema resolves true/false/null exactly as JSON does.",
                    "MUST",
                    "accept",
                    '{"ok":true,"no":false,"missing":null}',
                    decoded={"ok": True, "no": False, "missing": None},
                ),
                C(
                    "yaml12-yes-is-string",
                    "In the JSON/Core schema, yes is a string",
                    "10.2.2",
                    "JSON Schema",
                    f"{y12}#id2803231",
                    "Unlike YAML 1.1, the YAML 1.2 JSON schema does not resolve yes/no/on/off as booleans.",
                    "MUST",
                    "accept",
                    "flag: yes\n",
                    decoded={"flag": "yes"},
                    notes="PyYAML still uses YAML 1.1 implicit types, so it typically yields True. That is a 1.2 schema miss.",
                ),
                C(
                    "yaml12-no-sexagesimal",
                    "Sexagesimal is not a Core/JSON integer",
                    "10.2.1",
                    "Core Schema",
                    f"{y12}#id2804923",
                    "YAML 1.2 Core integers are decimal, hex, or octal — not sexagesimal.",
                    "MUST",
                    "accept",
                    "clock: 1:2\n",
                    decoded={"clock": "1:2"},
                    notes="A 1.1 loader that yields 62 fails this 1.2 expectation.",
                ),
                C(
                    "yaml12-literal-block",
                    "Literal block scalar keeps newlines",
                    "8.1.2",
                    "Literal Style",
                    f"{y12}#id2795688",
                    "The literal style (|) is the simplest, most restricted, and most readable scalar style for block text.",
                    "MUST",
                    "accept",
                    "note: |\n  line one\n  line two\n",
                    decoded={"note": "line one\nline two\n"},
                ),
                C(
                    "yaml12-folded-block",
                    "Folded block scalar folds newlines to spaces",
                    "8.1.3",
                    "Folded Style",
                    f"{y12}#id2796251",
                    "The folded style (>) is similar to literal but folded newlines become spaces.",
                    "MUST",
                    "accept",
                    "note: >\n  line one\n  line two\n",
                    decoded={"note": "line one line two\n"},
                ),
                C(
                    "yaml12-document-marker",
                    "Directives end / document start marker",
                    "9.1.1",
                    "Document Prefix",
                    f"{y12}#id2800130",
                    "A document may begin with ---.",
                    "MUST",
                    "accept",
                    "---\nharbor: kelp\n",
                    decoded={"harbor": "kelp"},
                ),
                C(
                    "yaml12-tab-indent",
                    "Tabs must not be used as indentation",
                    "6.1",
                    "Indentation Spaces",
                    f"{y12}#id2772347",
                    "In YAML block styles, structure is determined by indentation. Indentation is defined as space characters; tab characters must not be used.",
                    "MUST NOT",
                    "reject",
                    "harbor:\n\tkelp\n",
                ),
                C(
                    "yaml12-unmatched-bracket",
                    "Unbalanced flow collection is an error",
                    "7.4",
                    "Flow Collection Styles",
                    f"{y12}#id2791606",
                    "Flow sequences and mappings must be closed by the matching indicator.",
                    "MUST NOT",
                    "reject",
                    "[1, 2\n",
                ),
            ],
        },
    )
    dump(
        "yaml/v1.2.2.json",
        {
            "format": "yaml",
            "standard": "YAML 1.2.2",
            "version": "1.2.2",
            "standard_url": y122,
            "provenance": "original-work",
            "notes": (
                "YAML 1.2.2 (2021) is the current 1.2 revision (errata and editorial "
                "clarifications). The language is still 1.2."
            ),
            "cases": [
                C(
                    "yaml122-empty-mapping",
                    "Empty flow mapping",
                    "7.4.2",
                    "Flow Mappings",
                    f"{y122}#742-flow-mappings",
                    "A flow mapping is a mapping node represented in a compact flow style.",
                    "MUST",
                    "accept",
                    "{}\n",
                    decoded={},
                ),
                C(
                    "yaml122-empty-sequence",
                    "Empty flow sequence",
                    "7.4.1",
                    "Flow Sequences",
                    f"{y122}#741-flow-sequences",
                    "A flow sequence is a sequence node represented in a compact flow style.",
                    "MUST",
                    "accept",
                    "[]\n",
                    decoded=[],
                ),
                C(
                    "yaml122-json-number",
                    "JSON number tokens are YAML 1.2 numbers",
                    "10.2",
                    "JSON Schema",
                    f"{y122}#102-json-schema",
                    "The JSON schema is intended to be compatible with JSON.",
                    "MUST",
                    "accept",
                    "-1.5e2\n",
                    decoded=-150.0,
                ),
                C(
                    "yaml122-duplicate-key",
                    "Duplicate keys are an error in YAML 1.2",
                    "3.2.1.1",
                    "Mapping",
                    f"{y122}#3211-nodes",
                    "Mappings are an unordered association of unique keys to values. Duplicate keys are invalid.",
                    "MUST NOT",
                    "reject",
                    "harbor: 1\nharbor: 2\n",
                    notes="Many loaders keep the last value instead of erroring.",
                ),
                C(
                    "yaml122-alias-undefined",
                    "An alias without a prior anchor is an error",
                    "7.1",
                    "Alias Nodes",
                    f"{y122}#71-alias-nodes",
                    "An alias node refers to the most recent preceding node having the identified anchor.",
                    "MUST NOT",
                    "reject",
                    "second: *missing\n",
                ),
                C(
                    "yaml122-yes-string",
                    "1.2.2 Core/JSON: yes remains a string",
                    "10.2",
                    "JSON Schema",
                    f"{y122}#102-json-schema",
                    "The 1.2.2 JSON schema boolean tokens are true and false only.",
                    "MUST",
                    "accept",
                    "flag: yes\n",
                    decoded={"flag": "yes"},
                ),
                C(
                    "yaml122-tab-indent",
                    "Tabs are not indentation",
                    "6.1",
                    "Indentation Spaces",
                    f"{y122}#61-indentation-spaces",
                    "To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently.",
                    "MUST NOT",
                    "reject",
                    "harbor:\n\tkelp\n",
                ),
            ],
        },
    )


# ---------------------------------------------------------------------------
# TOML
# ---------------------------------------------------------------------------


def write_toml_suites() -> None:
    t05 = "https://toml.io/en/v0.5.0"
    t10 = "https://toml.io/en/v1.0.0"
    t11 = "https://toml.io/en/v1.1.0"

    dump(
        "toml/v0.5.0.json",
        {
            "format": "toml",
            "standard": "TOML 0.5.0",
            "version": "0.5.0",
            "standard_url": t05,
            "provenance": "original-work",
            "notes": "TOML v0.5.0 (2018) introduced dotted keys and is the last pre-1.0 spec still seen in the wild.",
            "cases": [
                C(
                    "toml05-kv",
                    "Bare key and basic string",
                    "Key/Value Pairs",
                    "Key/Value Pairs",
                    f"{t05}#keyvalue-pair",
                    "The equals sign, surrounded by whitespace, separates a key from a value.",
                    "MUST",
                    "accept",
                    'harbor = "kelp"\n',
                    decoded={"harbor": "kelp"},
                ),
                C(
                    "toml05-dotted-key",
                    "Dotted keys create nested tables",
                    "Keys",
                    "Keys",
                    f"{t05}#keys",
                    "A key may be either bare, quoted, or dotted. Dotted keys define a hierarchy of tables.",
                    "MUST",
                    "accept",
                    'site.harbor = "kelp"\n',
                    decoded={"site": {"harbor": "kelp"}},
                ),
                C(
                    "toml05-array",
                    "Array of integers",
                    "Array",
                    "Array",
                    f"{t05}#array",
                    "Arrays are square brackets with values separated by commas.",
                    "MUST",
                    "accept",
                    "counts = [1, 2, 3]\n",
                    decoded={"counts": [1, 2, 3]},
                ),
                C(
                    "toml05-table",
                    "Standard table header",
                    "Table",
                    "Table",
                    f"{t05}#table",
                    "Tables are collections of key/value pairs under a [header].",
                    "MUST",
                    "accept",
                    '[site]\nharbor = "kelp"\n',
                    decoded={"site": {"harbor": "kelp"}},
                ),
                C(
                    "toml05-inline-table",
                    "Inline table",
                    "Inline Table",
                    "Inline Table",
                    f"{t05}#inline-table",
                    "Inline tables are enclosed in curly braces.",
                    "MUST",
                    "accept",
                    'site = { harbor = "kelp", count = 3 }\n',
                    decoded={"site": {"harbor": "kelp", "count": 3}},
                ),
                C(
                    "toml05-bool",
                    "Boolean true/false",
                    "Boolean",
                    "Boolean",
                    f"{t05}#boolean",
                    "Booleans are true or false. Always lowercase.",
                    "MUST",
                    "accept",
                    "ok = true\n",
                    decoded={"ok": True},
                ),
                C(
                    "toml05-comment",
                    "Comments start with #",
                    "Comment",
                    "Comment",
                    f"{t05}#comment",
                    "A hash symbol marks the rest of the line as a comment.",
                    "MUST",
                    "accept",
                    'harbor = "kelp" # berth\n',
                    decoded={"harbor": "kelp"},
                ),
                C(
                    "toml05-trailing-comma-array",
                    "Trailing commas in arrays are not in v0.5",
                    "Array",
                    "Array",
                    f"{t05}#array",
                    "v0.5 arrays are comma-separated values; trailing commas became legal later.",
                    "MUST NOT",
                    "reject",
                    "counts = [1, 2,]\n",
                    notes="TOML 1.0 already allows this; a 0.5-only reject is historical.",
                ),
                C(
                    "toml05-bare-true-key-ok",
                    "Bare keys may look like other tokens if they are keys",
                    "Keys",
                    "Keys",
                    f"{t05}#keys",
                    "Bare keys may only contain ASCII letters, ASCII digits, underscores, and dashes.",
                    "MUST",
                    "accept",
                    'harbor-1 = "kelp"\n',
                    decoded={"harbor-1": "kelp"},
                ),
                C(
                    "toml05-missing-value",
                    "A key without a value is invalid",
                    "Key/Value Pairs",
                    "Key/Value Pairs",
                    f"{t05}#keyvalue-pair",
                    "Key/value pairs are on a single line; the value is required.",
                    "MUST NOT",
                    "reject",
                    "harbor =\n",
                ),
            ],
        },
    )
    dump(
        "toml/v1.0.0.json",
        {
            "format": "toml",
            "standard": "TOML 1.0.0",
            "version": "1.0.0",
            "standard_url": t10,
            "provenance": "original-work",
            "notes": "TOML v1.0.0 (2021) is the first stable spec. Python tomllib implements this version.",
            "cases": [
                C(
                    "toml10-basic-string",
                    "Basic string with escape",
                    "String",
                    "String",
                    f"{t10}#string",
                    r"Basic strings are surrounded by quotation marks. Escapes include \n, \t, \", \\, \uXXXX.",
                    "MUST",
                    "accept",
                    'note = "line\\nbreak"\n',
                    decoded={"note": "line\nbreak"},
                ),
                C(
                    "toml10-multiline-string",
                    "Multiline basic string",
                    "String",
                    "String",
                    f"{t10}#string",
                    "Multiline basic strings are surrounded by three quotation marks.",
                    "MUST",
                    "accept",
                    'note = """\nkelp\nbeds"""\n',
                    decoded={"note": "kelp\nbeds"},
                ),
                C(
                    "toml10-integer",
                    "Integer with underscores",
                    "Integer",
                    "Integer",
                    f"{t10}#integer",
                    "Underscores may be used to enhance readability of integers.",
                    "MUST",
                    "accept",
                    "count = 1_000\n",
                    decoded={"count": 1000},
                ),
                C(
                    "toml10-float",
                    "Fractional float",
                    "Float",
                    "Float",
                    f"{t10}#float",
                    "A float consists of an integer part followed by a fractional part and/or an exponent part.",
                    "MUST",
                    "accept",
                    "depth = 1.5\n",
                    decoded={"depth": 1.5},
                ),
                C(
                    "toml10-array-trailing-comma",
                    "Trailing commas in arrays are allowed in 1.0",
                    "Array",
                    "Array",
                    f"{t10}#array",
                    "Arrays can span multiple lines. A terminating comma (also called trailing comma) is permitted.",
                    "MUST",
                    "accept",
                    "counts = [1, 2,]\n",
                    decoded={"counts": [1, 2]},
                ),
                C(
                    "toml10-array-of-tables",
                    "Array of tables",
                    "Array of Tables",
                    "Array of Tables",
                    f"{t10}#array-of-tables",
                    "Double brackets declare an array of tables.",
                    "MUST",
                    "accept",
                    '[[berth]]\nname = "north"\n[[berth]]\nname = "south"\n',
                    decoded={"berth": [{"name": "north"}, {"name": "south"}]},
                ),
                C(
                    "toml10-offset-datetime",
                    "Offset date-time",
                    "Offset Date-Time",
                    "Offset Date-Time",
                    f"{t10}#offset-date-time",
                    "Offset date-times are RFC 3339.",
                    "MUST",
                    "accept",
                    "when = 1979-05-27T07:32:00Z\n",
                    notes="Decoded type is implementation-defined (datetime vs string). Accept-only.",
                ),
                C(
                    "toml10-inline-table-no-trailing-comma",
                    "Trailing commas in inline tables are invalid in 1.0",
                    "Inline Table",
                    "Inline Table",
                    f"{t10}#inline-table",
                    "No newlines are allowed between the curly braces unless they are valid within a value. Trailing commas are not permitted in 1.0 inline tables.",
                    "MUST NOT",
                    "reject",
                    'site = { harbor = "kelp", }\n',
                ),
                C(
                    "toml10-redefine-table",
                    "A table cannot be defined twice",
                    "Table",
                    "Table",
                    f"{t10}#table",
                    "Defining a table twice is invalid.",
                    "MUST NOT",
                    "reject",
                    "[site]\nharbor = 1\n[site]\ncount = 2\n",
                ),
                C(
                    "toml10-bare-space-key",
                    "Spaces in a bare key are invalid",
                    "Keys",
                    "Keys",
                    f"{t10}#keys",
                    "Bare keys may only contain ASCII letters, ASCII digits, underscores, and dashes.",
                    "MUST NOT",
                    "reject",
                    'harbor name = "kelp"\n',
                ),
                C(
                    "toml10-true-wrong-case",
                    "Boolean True is invalid",
                    "Boolean",
                    "Boolean",
                    f"{t10}#boolean",
                    "Booleans are true or false. Always lowercase.",
                    "MUST NOT",
                    "reject",
                    "ok = True\n",
                ),
            ],
        },
    )
    dump(
        "toml/v1.1.0.json",
        {
            "format": "toml",
            "standard": "TOML 1.1.0",
            "version": "1.1.0",
            "standard_url": t11,
            "provenance": "original-work",
            "notes": (
                "TOML v1.1.0 allows trailing commas and newlines in inline tables, "
                "\\xHH escapes, and optional seconds. Python tomllib is still 1.0."
            ),
            "cases": [
                C(
                    "toml11-inline-trailing-comma",
                    "Trailing comma in an inline table is valid in 1.1",
                    "Inline Table",
                    "Inline Table",
                    f"{t11}#inline-table",
                    "TOML 1.1 permits a trailing comma in an inline table.",
                    "MUST",
                    "accept",
                    'site = { harbor = "kelp", }\n',
                    decoded={"site": {"harbor": "kelp"}},
                ),
                C(
                    "toml11-inline-newline",
                    "Newlines inside inline tables are valid in 1.1",
                    "Inline Table",
                    "Inline Table",
                    f"{t11}#inline-table",
                    "TOML 1.1 allows newlines between key/value pairs of an inline table.",
                    "MUST",
                    "accept",
                    'site = {\n  harbor = "kelp"\n}\n',
                    decoded={"site": {"harbor": "kelp"}},
                ),
                C(
                    "toml11-hex-escape",
                    "\\xHH is a valid basic-string escape in 1.1",
                    "String",
                    "String",
                    f"{t11}#string",
                    r"TOML 1.1 adds \xHH (two hex digits) as a Unicode escape in basic strings.",
                    "MUST",
                    "accept",
                    'mark = "\\x41"\n',
                    decoded={"mark": "A"},
                ),
                C(
                    "toml11-array-trailing",
                    "Trailing commas in arrays remain valid",
                    "Array",
                    "Array",
                    f"{t11}#array",
                    "A terminating comma is permitted after the last array value.",
                    "MUST",
                    "accept",
                    "counts = [1, 2, 3,]\n",
                    decoded={"counts": [1, 2, 3]},
                ),
                C(
                    "toml11-still-no-duplicate-key",
                    "Duplicate keys remain invalid",
                    "Keys",
                    "Keys",
                    f"{t11}#keys",
                    "Defining a key twice is invalid.",
                    "MUST NOT",
                    "reject",
                    'harbor = "kelp"\nharbor = "rock"\n',
                ),
                C(
                    "toml11-unclosed-string",
                    "Unterminated basic string is invalid",
                    "String",
                    "String",
                    f"{t11}#string",
                    "A basic string must be closed by a quotation mark.",
                    "MUST NOT",
                    "reject",
                    'harbor = "kelp\n',
                ),
                C(
                    "toml11-true-case",
                    "Boolean True remains invalid",
                    "Boolean",
                    "Boolean",
                    f"{t11}#boolean",
                    "Booleans are true or false. Always lowercase.",
                    "MUST NOT",
                    "reject",
                    "ok = True\n",
                ),
            ],
        },
    )


# ---------------------------------------------------------------------------
# CBOR
# ---------------------------------------------------------------------------


def write_cbor_suites() -> None:
    r7049 = "https://www.rfc-editor.org/rfc/rfc7049"
    r8949 = "https://www.rfc-editor.org/rfc/rfc8949"

    # Appendix A encodings are IETF Code Components (tables of values).
    # Descriptions and ids here are original. See THIRD_PARTY_NOTICES.
    appendix = [
        ("0", "00", 0, "unsigned 0"),
        ("1", "01", 1, "unsigned 1"),
        ("10", "0a", 10, "unsigned 10"),
        ("23", "17", 23, "unsigned 23 (one-byte head)"),
        ("24", "1818", 24, "unsigned 24 (ai=24 + one byte)"),
        ("100", "1864", 100, "unsigned 100"),
        ("1000", "1903e8", 1000, "unsigned 1000"),
        ("minus-1", "20", -1, "negative 1 (major type 1)"),
        ("false", "f4", False, "simple false"),
        ("true", "f5", True, "simple true"),
        ("null", "f6", None, "simple null"),
        ("empty-bytes", "40", {"$hex": ""}, "empty byte string"),
        ("empty-text", "60", "", "empty text string"),
        ("text-a", "6161", "a", "text string 'a'"),
        ("empty-array", "80", [], "empty array"),
        ("array-1-2-3", "83010203", [1, 2, 3], "array of three unsigneds"),
        ("empty-map", "a0", {}, "empty map"),
    ]

    def appendix_cases(prefix: str, url: str) -> list[dict]:
        out = []
        for slug, hexv, decoded, title in appendix:
            out.append(
                C(
                    f"{prefix}-app-{slug}",
                    f"Appendix A: {title}",
                    "Appendix A",
                    "Examples of Encoded CBOR Data Items",
                    f"{url}#appendix-A",
                    "The RFC appendix lists diagnostic notation paired with the encoded byte string. This case checks that pair.",
                    "MUST",
                    "accept",
                    hexv,
                    input_encoding="hex",
                    decoded=decoded,
                )
            )
        return out

    dump(
        "cbor/rfc7049.json",
        {
            "format": "cbor",
            "standard": "RFC 7049",
            "version": "7049",
            "standard_url": r7049,
            "provenance": "original-work+ietf-appendix-A",
            "notes": (
                "RFC 7049 (October 2013) is the original CBOR specification. "
                "Appendix A encodings are IETF Code Components (Revised BSD)."
            ),
            "cases": appendix_cases("cbor7049", r7049)
            + [
                C(
                    "cbor7049-indef-array",
                    "Indefinite-length array of 1, 2 then break",
                    "2.2.1",
                    "Indefinite-Length Arrays and Maps",
                    f"{r7049}#section-2.2.1",
                    "An indefinite-length array is a head with additional information 31, then data items, then the break stop code 0xff.",
                    "MUST",
                    "accept",
                    "9f0102ff",
                    input_encoding="hex",
                    decoded=[1, 2],
                ),
                C(
                    "cbor7049-truncated-unsigned",
                    "Major type 0 with ai=24 but no following byte is not well-formed",
                    "2.1",
                    "Major Types",
                    f"{r7049}#section-2.1",
                    "Additional information 24 means one extra byte follows. A missing extra byte is not a well-formed data item.",
                    "MUST NOT",
                    "reject",
                    "18",
                    input_encoding="hex",
                ),
                C(
                    "cbor7049-break-alone",
                    "A break code is not a data item by itself",
                    "2.2",
                    "Indefinite Lengths",
                    f"{r7049}#section-2.2",
                    "The break stop code 0xff ends an indefinite-length item; it is not itself a value.",
                    "MUST NOT",
                    "reject",
                    "ff",
                    input_encoding="hex",
                ),
            ],
        },
    )
    dump(
        "cbor/rfc8949.json",
        {
            "format": "cbor",
            "standard": "RFC 8949",
            "version": "8949",
            "standard_url": r8949,
            "provenance": "original-work+ietf-appendix-A",
            "notes": (
                "RFC 8949 (December 2020) is STD 94 and obsoletes RFC 7049. "
                "It tightens well-formedness (e.g. simple values 24–31)."
            ),
            "cases": appendix_cases("cbor8949", r8949)
            + [
                C(
                    "cbor8949-indef-bytes",
                    "Indefinite-length byte string of two chunks",
                    "3.2.3",
                    "Indefinite-Length Byte Strings and Text Strings",
                    f"{r8949}#section-3.2.3",
                    "An indefinite-length byte string is major type 2 with ai=31, then definite-length byte-string chunks, then break.",
                    "MUST",
                    "accept",
                    "5f440102030443040506ff",
                    input_encoding="hex",
                    decoded={"$hex": "01020304040506"},
                    notes="RFC 8949 §3.2.3 example shape: 4-byte chunk 01020304 then 3-byte chunk 040506.",
                ),
                C(
                    "cbor8949-simple-24-unassigned",
                    "Simple values 24–31 are not well-formed",
                    "3.3",
                    "Floating-Point Numbers and Values with No Content",
                    f"{r8949}#section-3.3",
                    "An encoder MUST NOT issue two-byte sequences that start with 0xf8 and continue with a byte less than 0x20. These are not well-formed.",
                    "MUST NOT",
                    "reject",
                    "f800",
                    input_encoding="hex",
                ),
                C(
                    "cbor8949-truncated",
                    "Additional information 24 without the extra byte is not well-formed",
                    "3.1",
                    "Major Types",
                    f"{r8949}#section-3.1",
                    "ai=24 means a one-byte argument follows. End of input before that byte is not well-formed.",
                    "MUST NOT",
                    "reject",
                    "18",
                    input_encoding="hex",
                ),
                C(
                    "cbor8949-break-alone",
                    "Break is not a stand-alone data item",
                    "3.2.1",
                    "The 'break' Stop Code",
                    f"{r8949}#section-3.2.1",
                    "A well-formed data item cannot be the break stop code by itself.",
                    "MUST NOT",
                    "reject",
                    "ff",
                    input_encoding="hex",
                ),
                C(
                    "cbor8949-odd-map",
                    "A map must contain an even number of items (key/value pairs)",
                    "3.1",
                    "Major Types",
                    f"{r8949}#section-3.1",
                    "Major type 5 is a map of pairs of data items. A definite-length map of length 1 must contain two enclosed items.",
                    "MUST NOT",
                    "reject",
                    "a101",
                    input_encoding="hex",
                    notes="Head says one pair; only a key (1) follows.",
                ),
            ],
        },
    )


# ---------------------------------------------------------------------------
# MessagePack
# ---------------------------------------------------------------------------


def write_msgpack_suites() -> None:
    spec = "https://github.com/msgpack/msgpack/blob/master/spec.md"
    old = "https://github.com/msgpack/msgpack/blob/master/spec-old.md"

    dump(
        "msgpack/spec-2008-raw.json",
        {
            "format": "msgpack",
            "standard": "MessagePack (pre-2013 raw)",
            "version": "2008-raw",
            "standard_url": old,
            "provenance": "original-work",
            "notes": (
                "Early MessagePack used a single raw family for both text and bytes "
                "(fixraw / raw 16 / raw 32). There was no bin type."
            ),
            "cases": [
                C(
                    "mp08-pos-fixnum",
                    "Positive fixint 0..127",
                    "Type Chart",
                    "Positive FixNum",
                    f"{old}#type-chart",
                    "0xxxxxxx stores a 7-bit non-negative integer in a single byte.",
                    "MUST",
                    "accept",
                    "00",
                    input_encoding="hex",
                    decoded=0,
                ),
                C(
                    "mp08-neg-fixnum",
                    "Negative fixint -1",
                    "Type Chart",
                    "Negative FixNum",
                    f"{old}#type-chart",
                    "111xxxxx stores a 5-bit negative integer.",
                    "MUST",
                    "accept",
                    "ff",
                    input_encoding="hex",
                    decoded=-1,
                ),
                C(
                    "mp08-nil",
                    "nil is 0xc0",
                    "Type Chart",
                    "nil",
                    f"{old}#type-chart",
                    "nil is the single byte 0xc0.",
                    "MUST",
                    "accept",
                    "c0",
                    input_encoding="hex",
                    decoded=None,
                ),
                C(
                    "mp08-false-true",
                    "false 0xc2 / true 0xc3",
                    "Type Chart",
                    "Boolean",
                    f"{old}#type-chart",
                    "false is 0xc2; true is 0xc3.",
                    "MUST",
                    "accept",
                    "c3",
                    input_encoding="hex",
                    decoded=True,
                ),
                C(
                    "mp08-fixraw-a",
                    "fixraw of one ASCII byte (legacy raw)",
                    "Type Chart",
                    "FixRaw",
                    f"{old}#type-chart",
                    "101xxxxx is fix raw: 5-bit length plus that many bytes. Pre-2013 this is the only string/bytes family.",
                    "MUST",
                    "accept",
                    "a161",
                    input_encoding="hex",
                    decoded="a",
                    notes="Modern decoders treat fixstr the same way for UTF-8.",
                ),
                C(
                    "mp08-fixarray",
                    "fixarray of two integers",
                    "Type Chart",
                    "FixArray",
                    f"{old}#type-chart",
                    "1001xxxx is fix array: 4-bit length plus that many elements.",
                    "MUST",
                    "accept",
                    "920102",
                    input_encoding="hex",
                    decoded=[1, 2],
                ),
                C(
                    "mp08-fixmap",
                    "fixmap of one pair",
                    "Type Chart",
                    "FixMap",
                    f"{old}#type-chart",
                    "1000xxxx is fix map: 4-bit pair count plus key/value items.",
                    "MUST",
                    "accept",
                    "81a16101",
                    input_encoding="hex",
                    decoded={"a": 1},
                ),
                C(
                    "mp08-uint8",
                    "uint 8",
                    "Type Chart",
                    "uint 8",
                    f"{old}#type-chart",
                    "0xcc followed by one byte is an 8-bit unsigned integer.",
                    "MUST",
                    "accept",
                    "ccff",
                    input_encoding="hex",
                    decoded=255,
                ),
                C(
                    "mp08-truncated-uint8",
                    "uint 8 without the extra byte is invalid",
                    "Type Chart",
                    "uint 8",
                    f"{old}#type-chart",
                    "The uint 8 format requires a following byte.",
                    "MUST NOT",
                    "reject",
                    "cc",
                    input_encoding="hex",
                ),
                C(
                    "mp08-reserved-c1",
                    "0xc1 is reserved / never used",
                    "Type Chart",
                    "never used",
                    f"{old}#type-chart",
                    "0xc1 is reserved and is not a valid MessagePack value.",
                    "MUST NOT",
                    "reject",
                    "c1",
                    input_encoding="hex",
                ),
            ],
        },
    )
    dump(
        "msgpack/spec-2013-str-bin.json",
        {
            "format": "msgpack",
            "standard": "MessagePack (2013 str/bin/ext)",
            "version": "2013-str-bin",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": (
                "August 2013 split raw into str and bin and added extension types. "
                "This is the living spec family still used in industry."
            ),
            "cases": [
                C(
                    "mp13-fixstr",
                    "fixstr family (0xa0–0xbf)",
                    "str format family",
                    "fixstr",
                    f"{spec}#str-format-family",
                    "fixstr stores a UTF-8 string of up to 31 bytes in a one-byte head.",
                    "MUST",
                    "accept",
                    "a161",
                    input_encoding="hex",
                    decoded="a",
                ),
                C(
                    "mp13-str8",
                    "str 8",
                    "str format family",
                    "str 8",
                    f"{spec}#str-format-family",
                    "0xd9 + 8-bit length + UTF-8 bytes.",
                    "MUST",
                    "accept",
                    "d90161",
                    input_encoding="hex",
                    decoded="a",
                ),
                C(
                    "mp13-bin8-empty",
                    "bin 8 empty",
                    "bin format family",
                    "bin 8",
                    f"{spec}#bin-format-family",
                    "0xc4 + 8-bit length + raw bytes. Empty bin is c4 00.",
                    "MUST",
                    "accept",
                    "c400",
                    input_encoding="hex",
                    decoded={"$hex": ""},
                ),
                C(
                    "mp13-bin8-bytes",
                    "bin 8 of two bytes",
                    "bin format family",
                    "bin 8",
                    f"{spec}#bin-format-family",
                    "Binary is a distinct type from str; decoders must not coerce it to text.",
                    "MUST",
                    "accept",
                    "c40200ff",
                    input_encoding="hex",
                    decoded={"$hex": "00ff"},
                ),
                C(
                    "mp13-fixext1",
                    "fixext 1",
                    "ext format family",
                    "fixext 1",
                    f"{spec}#ext-format-family",
                    "0xd4 + type byte + 1 data byte.",
                    "MUST",
                    "accept",
                    "d40599",
                    input_encoding="hex",
                    notes="Observed type is library-specific (ExtType). Accept-only.",
                ),
                C(
                    "mp13-uint16",
                    "uint 16",
                    "int format family",
                    "uint 16",
                    f"{spec}#int-format-family",
                    "0xcd + 16-bit big-endian unsigned.",
                    "MUST",
                    "accept",
                    "cd0100",
                    input_encoding="hex",
                    decoded=256,
                ),
                C(
                    "mp13-int8",
                    "int 8 of -1",
                    "int format family",
                    "int 8",
                    f"{spec}#int-format-family",
                    "0xd0 + one signed byte.",
                    "MUST",
                    "accept",
                    "d0ff",
                    input_encoding="hex",
                    decoded=-1,
                ),
                C(
                    "mp13-float64",
                    "float 64 of 1.0",
                    "float format family",
                    "float 64",
                    f"{spec}#float-format-family",
                    "0xcb + IEEE 754 binary64 big-endian.",
                    "MUST",
                    "accept",
                    "cb3ff0000000000000",
                    input_encoding="hex",
                    decoded=1.0,
                ),
                C(
                    "mp13-truncated-str8",
                    "str 8 that claims one byte but has none",
                    "str format family",
                    "str 8",
                    f"{spec}#str-format-family",
                    "The declared length must be present in the remaining input.",
                    "MUST NOT",
                    "reject",
                    "d901",
                    input_encoding="hex",
                ),
                C(
                    "mp13-reserved-c1",
                    "0xc1 remains never used",
                    "Overview",
                    "never used",
                    f"{spec}#overview",
                    "0xc1 is the only reserved first byte and is not a valid value.",
                    "MUST NOT",
                    "reject",
                    "c1",
                    input_encoding="hex",
                ),
            ],
        },
    )
    dump(
        "msgpack/spec-2017-timestamp.json",
        {
            "format": "msgpack",
            "standard": "MessagePack (2017 timestamp ext)",
            "version": "2017-timestamp",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": (
                "August 2017 added timestamp extension type -1 (0xff) in 32-, 64-, "
                "and 96-bit layouts."
            ),
            "cases": [
                C(
                    "mp17-timestamp32-epoch",
                    "timestamp 32 at Unix epoch",
                    "Timestamp extension type",
                    "timestamp 32",
                    f"{spec}#timestamp-extension-type",
                    "timestamp 32 is fixext 4 (0xd6) + type 0xff + 32-bit seconds.",
                    "MUST",
                    "accept",
                    "d6ff00000000",
                    input_encoding="hex",
                    notes="Libraries may yield datetime, Timestamp, or ExtType. Accept-only.",
                ),
                C(
                    "mp17-timestamp64",
                    "timestamp 64 with nanoseconds",
                    "Timestamp extension type",
                    "timestamp 64",
                    f"{spec}#timestamp-extension-type",
                    "timestamp 64 is fixext 8 (0xd7) + type 0xff + 30-bit nsec and 34-bit sec.",
                    "MUST",
                    "accept",
                    "d7ff0000000100000001",
                    input_encoding="hex",
                    notes="Payload bits are defined by the spec; accept that the value decodes.",
                ),
                C(
                    "mp17-fixstr-still-valid",
                    "2017 is additive: fixstr still works",
                    "str format family",
                    "fixstr",
                    f"{spec}#str-format-family",
                    "The 2017 revision does not change the str family.",
                    "MUST",
                    "accept",
                    "a161",
                    input_encoding="hex",
                    decoded="a",
                ),
                C(
                    "mp17-bin8-still-valid",
                    "2017 is additive: bin 8 still works",
                    "bin format family",
                    "bin 8",
                    f"{spec}#bin-format-family",
                    "The 2017 revision does not change the bin family.",
                    "MUST",
                    "accept",
                    "c401ff",
                    input_encoding="hex",
                    decoded={"$hex": "ff"},
                ),
                C(
                    "mp17-truncated-timestamp32",
                    "timestamp 32 with a short payload is invalid",
                    "Timestamp extension type",
                    "timestamp 32",
                    f"{spec}#timestamp-extension-type",
                    "fixext 4 requires four data bytes after the type byte.",
                    "MUST NOT",
                    "reject",
                    "d6ff0000",
                    input_encoding="hex",
                ),
                C(
                    "mp17-reserved-c1",
                    "0xc1 is still never used",
                    "Overview",
                    "never used",
                    f"{spec}#overview",
                    "0xc1 is reserved.",
                    "MUST NOT",
                    "reject",
                    "c1",
                    input_encoding="hex",
                ),
            ],
        },
    )


def main() -> None:
    write_json_suites()
    write_yaml_suites()
    write_toml_suites()
    write_cbor_suites()
    write_msgpack_suites()


if __name__ == "__main__":
    main()
