#!/usr/bin/env python3
"""Original catalogs for UBJSON and Smile.

UBJSON: recreated from ubjson.org (Draft 12, Apache-2.0 spec). The
dmitry-ra/ubjson-test-suite tree has no OSI license and is not copied.

Smile: recreated from FasterXML smile-format-specification (BSD-2-Clause
spec). Token values are facts about the format; case ids and titles are
ours. Names are harbor / kelp.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "data"


def dump(rel: str, doc: dict) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT.parent)} ({len(doc['cases'])} cases)")


def C(**kwargs) -> dict:
    return kwargs


def write_ubjson() -> None:
    values = "https://ubjson.org/type-reference/value-types/"
    containers = "https://ubjson.org/type-reference/container-types/"
    spec = "https://ubjson.org/"
    draft8 = "https://ubjson.org/"

    literals = [
        C(
            id="ubj-null",
            title="Null is marker Z",
            section="Null Value",
            section_title="null",
            section_url=f"{values}#null-value",
            paragraph="The null value is the single byte 0x5A (ASCII Z).",
            requirement="MUST",
            expect="accept",
            input="5a",
            input_encoding="hex",
            decoded=None,
        ),
        C(
            id="ubj-true",
            title="True is marker T",
            section="Boolean Types",
            section_title="true",
            section_url=f"{values}#boolean-types",
            paragraph="The true value is the single byte 0x54 (ASCII T).",
            requirement="MUST",
            expect="accept",
            input="54",
            input_encoding="hex",
            decoded=True,
        ),
        C(
            id="ubj-false",
            title="False is marker F",
            section="Boolean Types",
            section_title="false",
            section_url=f"{values}#boolean-types",
            paragraph="The false value is the single byte 0x46 (ASCII F).",
            requirement="MUST",
            expect="accept",
            input="46",
            input_encoding="hex",
            decoded=False,
        ),
        C(
            id="ubj-empty",
            title="Empty buffer is not a value",
            section="Data Format",
            section_title="marker",
            section_url=spec,
            paragraph="Every value starts with a one-byte type marker.",
            requirement="MUST NOT",
            expect="reject",
            input="",
            input_encoding="hex",
        ),
        C(
            id="ubj-unknown-marker",
            title="0x00 is not a type marker",
            section="Type overview",
            section_title="markers",
            section_url=spec,
            paragraph="A type marker must be one of the defined ASCII markers.",
            requirement="MUST NOT",
            expect="reject",
            input="00",
            input_encoding="hex",
        ),
    ]
    draft8_only = [
        C(
            id="ubj8-byte",
            title="Draft 8 byte marker B",
            section="Numeric Types",
            section_title="byte (draft 8)",
            section_url=draft8,
            paragraph="Draft 8 stored a signed byte as marker B plus one payload byte. Draft 12 replaced B with i / U.",
            requirement="MUST",
            expect="accept",
            input="4207",
            input_encoding="hex",
            decoded=7,
            notes="Draft-8 marker. A Draft 12 decoder must reject B.",
        ),
        C(
            id="ubj8-string-s",
            title="Draft 8 string marker s",
            section="String Type",
            section_title="string (draft 8)",
            section_url=draft8,
            paragraph="Draft 8 used lowercase s plus a one-byte length. Draft 12 uses S plus an integer numeric length.",
            requirement="MUST",
            expect="accept",
            input="73046b656c70",
            input_encoding="hex",
            decoded="kelp",
        ),
        C(
            id="ubj8-array-a",
            title="Draft 8 length-prefixed array marker a",
            section="Container Types",
            section_title="array (draft 8)",
            section_url=draft8,
            paragraph="Draft 8 used marker a plus a count, not the streaming [ ] pair.",
            requirement="MUST",
            expect="accept",
            input="6100",
            input_encoding="hex",
            decoded=[],
        ),
    ]
    draft9 = [
        C(
            id="ubj-empty-array",
            title="Empty streaming array",
            section="Array Type",
            section_title="array",
            section_url=f"{containers}#array-type",
            paragraph="An array is marker [ then values then ]. The empty array is two bytes.",
            requirement="MUST",
            expect="accept",
            input="5b5d",
            input_encoding="hex",
            decoded=[],
        ),
        C(
            id="ubj-empty-object",
            title="Empty streaming object",
            section="Object Type",
            section_title="object",
            section_url=f"{containers}#object-type",
            paragraph="An object is marker { then key/value pairs then }. The empty object is two bytes.",
            requirement="MUST",
            expect="accept",
            input="7b7d",
            input_encoding="hex",
            decoded={},
        ),
        C(
            id="ubj-array-two",
            title="Array of two uint8 values",
            section="Array Type",
            section_title="array",
            section_url=f"{containers}#array-type",
            paragraph="Each element carries its own type marker unless the container is optimized.",
            requirement="MUST",
            expect="accept",
            input="5b550155025d",
            input_encoding="hex",
            decoded=[1, 2],
        ),
        C(
            id="ubj-object-n",
            title="Object n=7",
            section="Object Type",
            section_title="object",
            section_url=f"{containers}#object-type",
            paragraph="Each key is a string payload (integer length + UTF-8) without an S marker, then a typed value.",
            requirement="MUST",
            expect="accept",
            input="7b55016e55077d",
            input_encoding="hex",
            decoded={"n": 7},
        ),
        C(
            id="ubj-count-array",
            title="Optimized array with count",
            section="Optimized Format",
            section_title="count",
            section_url=f"{containers}#optimized-format",
            paragraph="Marker # plus an integer numeric is the element count. The closer ] is then omitted.",
            requirement="MUST",
            expect="accept",
            input="5b235503550155025503",
            input_encoding="hex",
            decoded=[1, 2, 3],
        ),
        C(
            id="ubj-count-object",
            title="Optimized object with count 1",
            section="Optimized Format",
            section_title="count",
            section_url=f"{containers}#optimized-format",
            paragraph="An object may declare # count and omit the closer.",
            requirement="MUST",
            expect="accept",
            input="7b23550155016e5507",
            input_encoding="hex",
            decoded={"n": 7},
        ),
        C(
            id="ubj-unclosed-array",
            title="Array without closer or count",
            section="Array Type",
            section_title="array",
            section_url=f"{containers}#array-type",
            paragraph="A streaming array must end with ] unless a count was given.",
            requirement="MUST NOT",
            expect="reject",
            input="5b5501",
            input_encoding="hex",
        ),
    ]
    draft12 = [
        C(
            id="ubj-uint8",
            title="uint8 marker U",
            section="Numeric Types",
            section_title="uint8",
            section_url=f"{values}#numeric-types",
            paragraph="Draft 12 uint8 is marker U plus one payload byte (0–255).",
            requirement="MUST",
            expect="accept",
            input="5507",
            input_encoding="hex",
            decoded=7,
        ),
        C(
            id="ubj-int8",
            title="int8 marker i",
            section="Numeric Types",
            section_title="int8",
            section_url=f"{values}#numeric-types",
            paragraph="int8 is marker i plus one two's-complement byte.",
            requirement="MUST",
            expect="accept",
            input="69ff",
            input_encoding="hex",
            decoded=-1,
        ),
        C(
            id="ubj-int16",
            title="int16 marker I",
            section="Numeric Types",
            section_title="int16",
            section_url=f"{values}#numeric-types",
            paragraph="int16 is marker I plus two big-endian bytes.",
            requirement="MUST",
            expect="accept",
            input="490007",
            input_encoding="hex",
            decoded=7,
        ),
        C(
            id="ubj-string",
            title="String S + uint8 length kelp",
            section="String Type",
            section_title="string",
            section_url=f"{values}#string-type",
            paragraph="A string is marker S, an integer numeric length, and that many UTF-8 bytes.",
            requirement="MUST",
            expect="accept",
            input="5355046b656c70",
            input_encoding="hex",
            decoded="kelp",
        ),
        C(
            id="ubj-char",
            title="Char marker C",
            section="Char Type",
            section_title="char",
            section_url=f"{values}#char-type",
            paragraph="A char is marker C plus one ASCII byte.",
            requirement="MUST",
            expect="accept",
            input="436b",
            input_encoding="hex",
            decoded="k",
        ),
        C(
            id="ubj-highprec",
            title="High-precision number H",
            section="Numeric Types",
            section_title="high-precision number",
            section_url=f"{values}#numeric-types",
            paragraph="H is a decimal written as a length-prefixed ASCII numeric string. Draft 12 added this type.",
            requirement="MUST",
            expect="accept",
            input="485504312e3235",
            input_encoding="hex",
            notes="Decoded type is library-defined (Decimal vs string). Accept-only.",
        ),
        C(
            id="ubj-noop-in-array",
            title="No-op N is skipped inside a container",
            section="No-Op Value",
            section_title="noop",
            section_url=f"{values}#no-op-value",
            paragraph="N is a valueless keep-alive. Inside a container it is not an element.",
            requirement="MUST",
            expect="accept",
            input="5b4e55075d",
            input_encoding="hex",
            decoded=[7],
        ),
        C(
            id="ubj-typed-uint8-array",
            title="Strongly typed uint8 array",
            section="Optimized Format",
            section_title="type and count",
            section_url=f"{containers}#optimized-format",
            paragraph="[$][U][#][count] then raw bytes with no per-element marker.",
            requirement="MUST",
            expect="accept",
            input="5b2455235503010203",
            input_encoding="hex",
            decoded={"$hex": "010203"},
        ),
        C(
            id="ubj-truncated-uint8",
            title="uint8 marker without payload",
            section="Numeric Types",
            section_title="uint8",
            section_url=f"{values}#numeric-types",
            paragraph="U requires one payload byte.",
            requirement="MUST NOT",
            expect="reject",
            input="55",
            input_encoding="hex",
        ),
        C(
            id="ubj-truncated-string",
            title="String shorter than declared length",
            section="String Type",
            section_title="string",
            section_url=f"{values}#string-type",
            paragraph="The declared length must be present in the remaining bytes.",
            requirement="MUST NOT",
            expect="reject",
            input="5355046b65",
            input_encoding="hex",
        ),
    ]

    dump(
        "ubjson/draft-8.json",
        {
            "format": "ubjson",
            "standard": "UBJSON Draft 8",
            "version": "draft-8",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": "Literals that survived later drafts, plus Draft 8 markers B / s / a. Recreated; dmitry-ra suite not copied.",
            "cases": literals + draft8_only,
        },
    )
    dump(
        "ubjson/draft-9.json",
        {
            "format": "ubjson",
            "standard": "UBJSON Draft 9",
            "version": "draft-9",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": "Streaming [ ] { } containers and # count (Draft 9+). Recreated.",
            "cases": literals + draft9,
        },
    )
    dump(
        "ubjson/draft-12.json",
        {
            "format": "ubjson",
            "standard": "UBJSON Draft 12",
            "version": "draft-12",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": "Current ubjson.org Draft 12: U, i, I, S, C, H, N, typed containers. Recreated.",
            "cases": literals + draft9 + draft12,
        },
    )


def write_smile() -> None:
    spec = "https://github.com/FasterXML/smile-format-specification/blob/master/smile-specification.md"
    header = f"{spec}#high-level-format"
    tokens = f"{spec}#tokens-value-mode"

    v10 = [
        C(
            id="smile-null",
            title="Literal null",
            section="Simple literals",
            section_title="null",
            section_url=tokens,
            paragraph="Value token 0x21 is null. The 4-byte header 3A 29 0A 00 precedes the token.",
            requirement="MUST",
            expect="accept",
            input="3a290a0021",
            input_encoding="hex",
            decoded=None,
        ),
        C(
            id="smile-true",
            title="Literal true",
            section="Simple literals",
            section_title="true",
            section_url=tokens,
            paragraph="Value token 0x23 is true.",
            requirement="MUST",
            expect="accept",
            input="3a290a0023",
            input_encoding="hex",
            decoded=True,
        ),
        C(
            id="smile-false",
            title="Literal false",
            section="Simple literals",
            section_title="false",
            section_url=tokens,
            paragraph="Value token 0x22 is false.",
            requirement="MUST",
            expect="accept",
            input="3a290a0022",
            input_encoding="hex",
            decoded=False,
        ),
        C(
            id="smile-empty-string",
            title="Empty string token",
            section="Simple literals",
            section_title="empty string",
            section_url=tokens,
            paragraph="Value token 0x20 is the empty string.",
            requirement="MUST",
            expect="accept",
            input="3a290a0020",
            input_encoding="hex",
            decoded="",
        ),
        C(
            id="smile-small-int-7",
            title="Small integer 7",
            section="Small integers",
            section_title="0xC0–0xDF",
            section_url=tokens,
            paragraph="Tokens 0xC0–0xDF are zigzag small integers. zigzag(7)=14 → 0xCE.",
            requirement="MUST",
            expect="accept",
            input="3a290a00ce",
            input_encoding="hex",
            decoded=7,
        ),
        C(
            id="smile-tiny-ascii",
            title="Tiny ASCII string kelp",
            section="Tiny ASCII",
            section_title="0x40–0x5F",
            section_url=tokens,
            paragraph="0x40+(len-1) then that many ASCII bytes. kelp is 4 bytes → 0x43.",
            requirement="MUST",
            expect="accept",
            input="3a290a00436b656c70",
            input_encoding="hex",
            decoded="kelp",
        ),
        C(
            id="smile-empty-array",
            title="Empty array",
            section="Structure markers",
            section_title="START/END_ARRAY",
            section_url=tokens,
            paragraph="0xF8 starts an array and 0xF9 ends it.",
            requirement="MUST",
            expect="accept",
            input="3a290a00f8f9",
            input_encoding="hex",
            decoded=[],
        ),
        C(
            id="smile-empty-object",
            title="Empty object",
            section="Structure markers",
            section_title="START/END_OBJECT",
            section_url=tokens,
            paragraph="0xFA starts an object and 0xFB ends it.",
            requirement="MUST",
            expect="accept",
            input="3a290a00fafb",
            input_encoding="hex",
            decoded={},
        ),
        C(
            id="smile-array-two",
            title="Array [1, 2]",
            section="Structure markers",
            section_title="START/END_ARRAY",
            section_url=tokens,
            paragraph="Array tokens surround value tokens. zigzag(1)=2 → 0xC2; zigzag(2)=4 → 0xC4.",
            requirement="MUST",
            expect="accept",
            input="3a290a00f8c2c4f9",
            input_encoding="hex",
            decoded=[1, 2],
        ),
        C(
            id="smile-object-n",
            title="Object n=7",
            section="Key tokens",
            section_title="short ASCII names",
            section_url=f"{spec}#tokens-key-mode",
            paragraph="A one-byte field name uses key token 0x80 plus the ASCII byte, then a value token.",
            requirement="MUST",
            expect="accept",
            input="3a290a00fa806ecefb",
            input_encoding="hex",
            decoded={"n": 7},
        ),
        C(
            id="smile-no-header",
            title="Missing smiley header",
            section="Header",
            section_title="4-byte header",
            section_url=header,
            paragraph="A Smile section starts with 0x3A 0x29 0x0A and a flags byte.",
            requirement="MUST NOT",
            expect="reject",
            input="21",
            input_encoding="hex",
        ),
        C(
            id="smile-bad-magic",
            title="Header is not :)\\n",
            section="Header",
            section_title="4-byte header",
            section_url=header,
            paragraph="Bytes 0–2 must be 0x3A 0x29 0x0A.",
            requirement="MUST NOT",
            expect="reject",
            input="3a280a0021",
            input_encoding="hex",
        ),
        C(
            id="smile-truncated-header",
            title="Truncated header",
            section="Header",
            section_title="4-byte header",
            section_url=header,
            paragraph="The header is four bytes.",
            requirement="MUST NOT",
            expect="reject",
            input="3a290a",
            input_encoding="hex",
        ),
        C(
            id="smile-empty",
            title="Empty buffer is not Smile",
            section="Header",
            section_title="4-byte header",
            section_url=header,
            paragraph="There is no empty Smile document; the header is required.",
            requirement="MUST NOT",
            expect="reject",
            input="",
            input_encoding="hex",
        ),
        C(
            id="smile-unclosed-array",
            title="Array without END_ARRAY",
            section="Structure markers",
            section_title="START/END_ARRAY",
            section_url=tokens,
            paragraph="Every 0xF8 must be matched by 0xF9.",
            requirement="MUST NOT",
            expect="reject",
            input="3a290a00f8",
            input_encoding="hex",
        ),
    ]
    shared = [
        C(
            id="smile-shared-header-object",
            title="Header bit 0 enables shared property names",
            section="Header",
            section_title="flags byte",
            section_url=header,
            paragraph="Flags bit 0 (mask 0x01) means the encoder recorded property names for back-references.",
            requirement="MUST",
            expect="accept",
            input="3a290a01fa806ec2fb",
            input_encoding="hex",
            decoded={"n": 1},
        ),
        C(
            id="smile-shared-two-objects",
            title="Second object may back-reference key n",
            section="Shared names",
            section_title="short shared key",
            section_url=f"{spec}#tokens-key-mode",
            paragraph="After a property name of length ≤ 64, a later key may be a 1-byte back-reference 0x40+index.",
            requirement="MUST",
            expect="accept",
            input="3a290a01f8fa806ec2fbfa40c4fbf9",
            input_encoding="hex",
            decoded=[{"n": 1}, {"n": 2}],
        ),
        C(
            id="smile-shared-repeat-inline",
            title="Repeating the key bytes is still valid",
            section="Shared names",
            section_title="short ASCII names",
            section_url=f"{spec}#tokens-key-mode",
            paragraph="Shared-name mode does not forbid writing the key again in full.",
            requirement="MUST",
            expect="accept",
            input="3a290a01f8fa806ec2fbfa806ec4fbf9",
            input_encoding="hex",
            decoded=[{"n": 1}, {"n": 2}],
        ),
        C(
            id="smile-shared-ref-without-table",
            title="Shared value ref 0x01 with empty table",
            section="Short Shared Value",
            section_title="0x01–0x1F",
            section_url=tokens,
            paragraph="Token 0x01 is a back-reference. With no prior string it is not well-formed.",
            requirement="MUST NOT",
            expect="reject",
            input="3a290a0001",
            input_encoding="hex",
        ),
    ]
    v104 = [
        C(
            id="smile-int32-31",
            title="32-bit integer token 0x24",
            section="Integral numbers",
            section_title="0x24",
            section_url=tokens,
            paragraph="0x24 is a zigzag VInt 32-bit integer. 31 encodes as 0x24 0xBE.",
            requirement="MUST",
            expect="accept",
            input="3a290a0024be",
            input_encoding="hex",
            decoded=31,
        ),
        C(
            id="smile-float32",
            title="32-bit float token 0x28",
            section="Floating point",
            section_title="0x28",
            section_url=tokens,
            paragraph="0x28 is a 5-byte 7-bit-safe IEEE-754 binary32. 1.0.4/1.0.7 clarify the padding.",
            requirement="MUST",
            expect="accept",
            input="3a290a00280000007e03",
            input_encoding="hex",
            decoded=1.5,
        ),
        C(
            id="smile-end-marker",
            title="0xFF after a value is end-of-content",
            section="Header",
            section_title="optional end marker",
            section_url=header,
            paragraph="0xFF is an optional end marker and is treated as end-of-stream, not a value.",
            requirement="MUST",
            expect="accept",
            input="3a290a0021ff",
            input_encoding="hex",
            decoded=None,
        ),
        C(
            id="smile-reserved-fe",
            title="0xFE is reserved",
            section="Low-level format",
            section_title="reserved bytes",
            section_url=f"{spec}#low-level-format",
            paragraph="0xFE is reserved and is not a value token.",
            requirement="MUST NOT",
            expect="reject",
            input="3a290a00fe",
            input_encoding="hex",
        ),
        C(
            id="smile-token-00",
            title="0x00 is not a value token",
            section="Short Shared Value",
            section_title="0x00 unused",
            section_url=tokens,
            paragraph="0x00 is not used as a short shared-value token in this version.",
            requirement="MUST NOT",
            expect="reject",
            input="3a290a0000",
            input_encoding="hex",
        ),
        C(
            id="smile-version-nibble",
            title="Version nibble must be 0",
            section="Header",
            section_title="version bits",
            section_url=header,
            paragraph="Bits 4–7 of the flags byte are the format version. Only 0x00 is defined.",
            requirement="MUST NOT",
            expect="reject",
            input="3a290a1021",
            input_encoding="hex",
        ),
        C(
            id="smile-object-harbor",
            title="Object harbor=kelp",
            section="Key tokens",
            section_title="short ASCII names",
            section_url=f"{spec}#tokens-key-mode",
            paragraph="A 6-byte field name uses key token 0x85 plus the ASCII bytes, then a tiny-ASCII value.",
            requirement="MUST",
            expect="accept",
            input="3a290a00fa85686172626f72436b656c70fb",
            input_encoding="hex",
            decoded={"harbor": "kelp"},
        ),
    ]

    dump(
        "smile/1.0.json",
        {
            "format": "smile",
            "standard": "Smile 1.0",
            "version": "1.0",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": "Header + literals + tiny ASCII + containers from the 1.0 token table. Original values.",
            "cases": v10,
        },
    )
    dump(
        "smile/1.0-shared.json",
        {
            "format": "smile",
            "standard": "Smile 1.0 shared names",
            "version": "1.0-shared",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": "Header bit 0 (shared property names) and back-references.",
            "cases": shared + [c for c in v10 if c["id"] in {"smile-object-n", "smile-no-header"}],
        },
    )
    dump(
        "smile/1.0.4.json",
        {
            "format": "smile",
            "standard": "Smile 1.0.4",
            "version": "1.0.4",
            "standard_url": spec,
            "provenance": "original-work",
            "notes": "1.0.4 clarifications: 0x24/0x28 numbers, 0xFF end marker, reserved 0xFE, version nibble.",
            "cases": v10[:8] + v104,
        },
    )


def main() -> None:
    write_ubjson()
    write_smile()


if __name__ == "__main__":
    main()
