#ifndef TINYCBOR_PREF_H
#define TINYCBOR_PREF_H
#define cbor_encode_byte_string tc_cbor_encode_byte_string
#define cbor_encode_floating_point tc_cbor_encode_floating_point
#define cbor_encode_int tc_cbor_encode_int
#define cbor_encode_negative_int tc_cbor_encode_negative_int
#define cbor_encoder_close_container tc_cbor_encoder_close_container
#define cbor_encoder_close_container_checked tc_cbor_encoder_close_container_checked
#define cbor_encoder_create_array tc_cbor_encoder_create_array
#define cbor_encoder_create_map tc_cbor_encoder_create_map
#define cbor_encoder_init tc_cbor_encoder_init
#define cbor_encoder_init_writer tc_cbor_encoder_init_writer
#define cbor_encode_simple_value tc_cbor_encode_simple_value
#define cbor_encode_tag tc_cbor_encode_tag
#define cbor_encode_text_string tc_cbor_encode_text_string
#define cbor_encode_uint tc_cbor_encode_uint
#define cbor_error_string tc_cbor_error_string
#define cbor_parser_init tc_cbor_parser_init
#define cbor_parser_init_reader tc_cbor_parser_init_reader
#define cbor_value_advance tc_cbor_value_advance
#define cbor_value_advance_fixed tc_cbor_value_advance_fixed
#define _cbor_value_begin_string_iteration tc__cbor_value_begin_string_iteration
#define cbor_value_calculate_string_length tc_cbor_value_calculate_string_length
#define _cbor_value_copy_string tc__cbor_value_copy_string
#define _cbor_value_decode_int64_internal tc__cbor_value_decode_int64_internal
#define _cbor_value_dup_string tc__cbor_value_dup_string
#define cbor_value_enter_container tc_cbor_value_enter_container
#define _cbor_value_finish_string_iteration tc__cbor_value_finish_string_iteration
#define cbor_value_get_int64_checked tc_cbor_value_get_int64_checked
#define cbor_value_get_int_checked tc_cbor_value_get_int_checked
#define _cbor_value_get_string_chunk tc__cbor_value_get_string_chunk
#define _cbor_value_get_string_chunk_size tc__cbor_value_get_string_chunk_size
#define cbor_value_leave_container tc_cbor_value_leave_container
#define cbor_value_map_find_value tc_cbor_value_map_find_value
#define cbor_value_reparse tc_cbor_value_reparse
#define cbor_value_skip_tag tc_cbor_value_skip_tag
#define cbor_value_text_string_equals tc_cbor_value_text_string_equals
#define cbor_value_to_pretty_stream tc_cbor_value_to_pretty_stream
#define cbor_value_validate_basic tc_cbor_value_validate_basic
#include "cbor.h"
#endif
