use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Prefer vendored protoc so local/CI builds do not require a system install.
    if let Ok(path) = protoc_bin_vendored::protoc_bin_path() {
        std::env::set_var("PROTOC", path);
    }
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    // Data Model v2 protobuf schema (shared under schemas/v2/protobuf).
    let proto = manifest.join("../schemas/v2/protobuf/benchmark_v2.proto");
    if proto.is_file() {
        prost_build::Config::new().compile_protos(
            &[&proto],
            &[manifest.join("../schemas/v2/protobuf")],
        )?;
        println!("cargo:rerun-if-changed={}", proto.display());
    } else {
        return Err(
            "missing schemas/v2/protobuf/benchmark_v2.proto for prost (relative to rust/)".into(),
        );
    }

    // Emit locked crate versions for CSV SerializerVersion (from Cargo.lock).
    write_dep_versions(&manifest)?;
    println!("cargo:rerun-if-changed=Cargo.lock");
    Ok(())
}

/// Parse top-level package entries from Cargo.lock (v3 format).
fn write_dep_versions(manifest: &std::path::Path) -> Result<(), Box<dyn std::error::Error>> {
    let lock_path = manifest.join("Cargo.lock");
    let text = fs::read_to_string(&lock_path).unwrap_or_default();
    let mut versions: HashMap<String, String> = HashMap::new();
    let mut cur_name: Option<String> = None;
    for line in text.lines() {
        let line = line.trim();
        if line == "[[package]]" {
            cur_name = None;
            continue;
        }
        if let Some(rest) = line.strip_prefix("name = \"") {
            if let Some(end) = rest.find('"') {
                cur_name = Some(rest[..end].to_string());
            }
        } else if let Some(rest) = line.strip_prefix("version = \"") {
            if let (Some(name), Some(end)) = (cur_name.as_ref(), rest.find('"')) {
                // First occurrence in lock is the resolved package version.
                versions
                    .entry(name.clone())
                    .or_insert_with(|| rest[..end].to_string());
            }
        }
    }

    let wanted = [
        "serde_json",
        "simd-json",
        "sonic-rs",
        "rmp-serde",
        "ciborium",
        "bincode",
        "postcard",
        "bitcode",
        "flexbuffers",
        "rkyv",
        "minicbor",
        "prost",
        "serde_avro_fast",
        "bson",
        "nanoserde",
        "speedy",
    ];
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    let out = out_dir.join("dep_versions.rs");
    let mut body = String::from(
        "/// Crate versions from Cargo.lock (generated by build.rs).\n\
         pub fn crate_version(name: &str) -> &'static str {\n\
             match name {\n",
    );
    for w in wanted {
        let ver = versions.get(w).map(|s| s.as_str()).unwrap_or("");
        body.push_str(&format!("        \"{w}\" => \"{ver}\",\n"));
    }
    body.push_str("        _ => \"\",\n    }\n}\n");
    fs::write(out, body)?;
    Ok(())
}
