kotlinx.serialization.json.Json=${kotlinxSerialization}
kotlinx.serialization.cbor.Cbor=${kotlinxSerialization}
kotlinx.serialization.protobuf.ProtoBuf=${kotlinxSerialization}
kotlinx.serialization.properties.Properties=${kotlinxSerialization}
kotlinx.serialization.hocon.Hocon=${kotlinxSerialization}
com.charleskorn.kaml.Yaml=${kaml}
org.msgpack.jackson.dataformat.MessagePackMapper=${msgpack}
com.google.flatbuffers.FlatBufferBuilder=${flatbuffers}
org.capnproto.Serialize=${capnproto}
com.google.protobuf.kotlin.DslProxy=${protobuf}
com.fasterxml.jackson.databind.ObjectMapper=${jackson}
com.fasterxml.jackson.dataformat.cbor.databind.CBORMapper=${jackson}
com.fasterxml.jackson.dataformat.ion.IonObjectMapper=${jackson}
com.google.gson.Gson=${gson}
com.squareup.moshi.Moshi=${moshi}
com.esotericsoftware.kryo.Kryo=${kryo}
org.apache.fory.Fory=${fory}
io.protostuff.ProtostuffIOUtil=${protostuff}
com.google.protobuf.MessageLite=${protobuf}
org.apache.avro.Schema=${avro}
com.github.avro4k.Avro=${avro4k}
com.github.jershell.kbson.KBson=${kbson}
net.orandja.obor.codec.Cbor=${obor}
net.peanuuutz.tomlkt.Toml=${tomlkt}
com.amazon.ion.IonSystem=${ionJava}
org.apache.thrift.TSerializer=${thrift}
default=unknown
