{
  "type": "record",
  "name": "ObjectGraph",
  "namespace": "benchmark_data",
  "fields": [
    {"name": "root", "type": "int"},
    {
      "name": "nodes",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "GraphNodeData",
          "fields": [
            {"name": "Name", "type": "string"},
            {"name": "Parent", "type": "int"},
            {"name": "Related", "type": "int"},
            {"name": "Children", "type": {"type": "array", "items": "int"}}
          ]
        }
      }
    }
  ]
}
